name: Bakehouse CI/CD Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  id-token: write

env:
  BAKEHOUSE_STACK_NAME: mitali-chavan-bakehouse
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: ./install.sh

  deploy:
    name: Synth & Deploy CDK App
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: ./install.sh

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Synth CDK Stack
        run: npx cdk synth

      - name: Deploy CDK Stack
        run: npx cdk deploy --all --require-approval never --on-failure DELETE

      - name: Bootstrap DB
        run: |
          aws lambda invoke \
            --region eu-west-2 \
            --function-name ${{ env.BAKEHOUSE_STACK_NAME}}-bootstrap-lambda \
            --cli-binary-format raw-in-base64-out \
            --payload "{}" \
            output.json

  test:
    name: Run Playwright & K6 Tests
    needs: deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Project Dependencies
        run: ./install.sh

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright Tests
        continue-on-error: true
        run: npm run test:e2e

      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 10

      - name: Setup K6
        uses: grafana/setup-k6-action@v1

      - name: Run Basic K6 Test
        uses: grafana/run-k6-action@v1
        with:
          path: test/k6/basic-example.js
      
      - name: Run Scenario K6 Test
        uses: grafana/run-k6-action@v1
        with:
          path: test/k6/scenario-example.js
