name: Bakehouse CI/CD Pipeline

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: eu-west-2
  BAKEHOUSE_STACK_NAME: mitali-chavan-bakehouse
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_ARN }}
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: ./install.sh

  deploy:
    name: Synth & Deploy CDK App
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    environment:
      name: prod

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: ./install.sh

      - name: Configure AWS Credentials Using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Check AWS Identity
        run: aws sts get-caller-identity

      - name: Synth CDK Stack
        run: npx cdk synth

      - name: Deploy CDK Stack
        run: npx cdk deploy --all --require-approval never

      - name: Bootstrap DB
        run: |
          aws lambda invoke \
            --region eu-west-2 \
            --function-name mitali-chavan-bakehouse-bootstrap-lambda \
            --cli-binary-format raw-in-base64-out \
            --payload "{}" \
            output.json
